### ISSUE TITLE
[Bug] 이력관리에서 화면이 깨집니다

### ISSUE THREAD

**Issue by kyujonglee** [scd7896/Yapp_front#1]
<img width="794" alt="스크린샷 2020-03-04 오후 3 20 36" src="https://user-images.githubusercontent.com/36789429/75850954-d6e29680-5e2b-11ea-929f-f7c0d5fa2b1c.png">

**Comment by jun094** [comment]
모바일 화면인가요??

**Comment by jun094** [comment]
해결완료했습니다..!
